services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - squirrels-mortgage
      - squirrels-weather
      - squirrels-expenses
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    networks:
      - squirrels-network

  squirrels-mortgage:
    build:
      context: ./sqrl-mortgage-analysis
      dockerfile: Dockerfile
    image: squirrels-mortgage:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    networks:
      - squirrels-network

  squirrels-weather:
    build:
      context: ./sqrl-weather-analytics
      dockerfile: Dockerfile
    image: squirrels-weather:latest
    restart: unless-stopped
    volumes:
      - ~/volumes/sqrl-weather-analytics/.env.local:/app/.env.local:ro
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    networks:
      - squirrels-network

  squirrels-expenses:
    build:
      context: ./sqrl-expenses
      dockerfile: Dockerfile
    image: squirrels-expenses:latest
    restart: unless-stopped
    volumes:
      - ~/volumes/sqrl-expenses/.env.local:/app/.env.local:ro
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    networks:
      - squirrels-network

networks:
  squirrels-network:
    driver: bridge 