services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx-mortgage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
      - C:/nginx-certs:/etc/nginx/certs:ro
    depends_on:
      - squirrels-mortgage
    networks:
      - mortgage-network

  squirrels-mortgage:
    build:
      context: .
      dockerfile: Dockerfile
    image: squirrels-mortgage:latest
    container_name: squirrels-mortgage
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
      - ./target:/app/target
    networks:
      - mortgage-network

networks:
  mortgage-network:
    driver: bridge 