sources:
  - name: src_weather_data
    description: A table containing weather data
    table: weather_data

    update_hints:
      increasing_column: id

    columns:
      - name: id
        type: INTEGER
        description: The unique identifier for each row

      - name: city
        type: STRING
        description: The city name

      - name: recorded_date
        type: DATE
        description: The date of the temperature measurement

      - name: temperature
        type: FLOAT
        description: The temperature
